FROM kusumoto/docker-ionic-android-sdk

ENV DEBIAN_FRONTEND noninteractive

LABEL maintainer="Edward Sargsyan <edward.sarkisyan@gmail.com>"

USER root

RUN apt update --fix-missing && \
    apt install -y curl

RUN apt install --reinstall -y software-properties-common && \
    add-apt-repository ppa:openjdk-r/ppa && \
    apt update && \
    apt install -y openjdk-11-jdk

RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.7/install.sh | bash

RUN NVM_DIR="$HOME/.nvm" && \
    [ -s "$NVM_DIR/nvm.sh" ] && \
	\. "$NVM_DIR/nvm.sh" && \
	nvm install v14.21.3